version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3307"
    networks:
      - dockercompose

  backend:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "//home//bsp//Documents//Docker//curso-docker//S_COMPOSE//6_bind_mount_compose//flask:/app"
    networks:
      - dockercompose

networks:
  dockercompose: